const APPLICATION_STATUS = Object.freeze({
  APPLIED: "APPLIED",
  SCREENING: "SCREENING",
  CONTACTED: "CONTACTED",
  INTERVIEW_SCHEDULED: "INTERVIEW_SCHEDULED",
  INTERVIEW_COMPLETED: "INTERVIEW_COMPLETED",
  HIRED: "HIRED",
  REJECTED: "REJECTED",
  WITHDRAWN: "WITHDRAWN",
});

export default APPLICATION_STATUS;
