const EMPLOYMENT_TYPE = Object.freeze({
  FULL_TIME: "FULL_TIME",
  PART_TIME: "PART_TIME",
  INTERNSHIP: "INTERNSHIP",
  CONTRACT: "CONTRACT",
  TEMPORARY: "TEMPORARY",
  FREELANCE: "FREELANCE",
  SEASONAL: "SEASONAL",
  APPRENTICESHIP: "APPRENTICESHIP",
});

export default EMPLOYMENT_TYPE;
