const EXPERIENCE_LEVEL = Object.freeze({
  NO_EXPERIENCE: "NO_EXPERIENCE",
  UNDER_1_YEAR: "UNDER_1_YEAR",
  ONE_TO_THREE_YEARS: "ONE_TO_THREE_YEARS",
  THREE_TO_FIVE_YEARS: "THREE_TO_FIVE_YEARS",
  FIVE_TO_TEN_YEARS: "FIVE_TO_TEN_YEARS",
  OVER_TEN_YEARS: "OVER_TEN_YEARS",
});

export default EXPERIENCE_LEVEL;
