const JOB_STATUS = Object.freeze({
  DRAFT: "DRAFT",
  PENDING_APPROVAL: "PENDING_APPROVAL",
  PUBLISHED: "PUBLISHED",
  CLOSED: "CLOSED",
  EXPIRED: "EXPIRED",
});

const OUTSTANDING_PRIMARY_JOB_STATUSES = Object.freeze([
  JOB_STATUS.DRAFT,
  JOB_STATUS.PENDING_APPROVAL,
  JOB_STATUS.PUBLISHED,
]);

export { OUTSTANDING_PRIMARY_JOB_STATUSES };

export default JOB_STATUS;
