const NOTIFICATION_TYPE = Object.freeze({
  DIRECT_APPLICATION_CREATED: "DIRECT_APPLICATION_CREATED",
  APPLICATION_ASSIGNED: "APPLICATION_ASSIGNED",
  APPLICATION_REASSIGNED: "APPLICATION_REASSIGNED",
  APPLICATION_UNASSIGNED: "APPLICATION_UNASSIGNED",
  APPLICATION_STATUS_CHANGED: "APPLICATION_STATUS_CHANGED",
  APPLICATION_HIRED: "APPLICATION_HIRED",
  APPLICATION_REJECTED: "APPLICATION_REJECTED",
  APPLICATION_WITHDRAWN: "APPLICATION_WITHDRAWN",
  INTERVIEW_AVAILABILITY_REQUESTED: "INTERVIEW_AVAILABILITY_REQUESTED",
  INTERVIEW_AVAILABILITY_SUBMITTED: "INTERVIEW_AVAILABILITY_SUBMITTED",
  INTERVIEW_SCHEDULE_CREATED: "INTERVIEW_SCHEDULE_CREATED",
  INTERVIEW_SCHEDULE_CHANGED: "INTERVIEW_SCHEDULE_CHANGED",
  INTERVIEW_SCHEDULE_CONFIRMED: "INTERVIEW_SCHEDULE_CONFIRMED",
  INTERVIEW_SCHEDULE_DECLINED: "INTERVIEW_SCHEDULE_DECLINED",
  CHAT_MESSAGE_CREATED: "CHAT_MESSAGE_CREATED",
});

export default NOTIFICATION_TYPE;
